# Generated by Django 3.2.4 on 2021-06-27 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mashing',
        ),
    ]
