# Generated by Django 3.2.5 on 2021-08-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_delete_mashing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Numer'),
        ),
    ]