# Generated by Django 3.2.7 on 2021-09-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_alter_batch_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-id'], 'verbose_name': 'Warka', 'verbose_name_plural': 'Warki'},
        ),
        migrations.AlterModelOptions(
            name='measurementblg',
            options={'ordering': ['-id'], 'verbose_name': 'Pomiar BLG', 'verbose_name_plural': 'Pomiary BLG'},
        ),
    ]