# Generated by Django 3.2.7 on 2021-09-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210606_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id'], 'verbose_name': 'Artykuł', 'verbose_name_plural': 'Artykuły'},
        ),
    ]
