# Generated by Django 3.2.7 on 2021-09-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210711_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-id'], 'verbose_name': 'Profil Użytkownika', 'verbose_name_plural': 'Profile Użytkownika'},
        ),
    ]
