# Generated by Django 3.2.3 on 2021-06-06 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_auto_20210606_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='boiled_wort_amount',
            field=models.FloatField(verbose_name='Ilość gotowanej brzeczki'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='boiling_losses',
            field=models.FloatField(verbose_name='Straty gotowania'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='boiling_time',
            field=models.PositiveSmallIntegerField(verbose_name='Czas gotowania'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cold_hop_losses',
            field=models.FloatField(verbose_name='Straty chmielenia na zimno'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='creation_date',
            field=models.DateTimeField(verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='evaporation_rate',
            field=models.FloatField(verbose_name='Szybkość parowania'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='expected_beer_amount',
            field=models.FloatField(verbose_name='Oczekiwana ilość piwa'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fermentation_losses',
            field=models.FloatField(verbose_name='Straty fermentacji'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='mashing_performance',
            field=models.FloatField(verbose_name='Wydajność zacierania'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notatki'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.style', verbose_name='Styl'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='water_to_grain_ratio',
            field=models.FloatField(verbose_name='Stosunek wody do ziarna'),
        ),
    ]
