# Generated by Django 3.2.5 on 2021-08-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210627_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('m', 'Zacieranie'), ('e', 'Ekstrakty'), ('b', 'Brewkit')], max_length=1, null=True, verbose_name='Typ'),
        ),
    ]
