# Generated by Django 3.2.7 on 2021-09-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hops',
            options={'ordering': ['-id'], 'verbose_name': 'Chmiel', 'verbose_name_plural': 'Chmiele'},
        ),
        migrations.AlterModelOptions(
            name='malt',
            options={'ordering': ['-id'], 'verbose_name': 'Słód', 'verbose_name_plural': 'Słody'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['-id'], 'verbose_name': 'Producent', 'verbose_name_plural': 'Producenci'},
        ),
        migrations.AlterModelOptions(
            name='mashing',
            options={'ordering': ['-id'], 'verbose_name': 'Zacieranie', 'verbose_name_plural': 'Zacierania'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-id'], 'verbose_name': 'Receptura', 'verbose_name_plural': 'Receptury'},
        ),
        migrations.AlterModelOptions(
            name='recipehops',
            options={'ordering': ['-id'], 'verbose_name': 'Chmiel', 'verbose_name_plural': 'Chmiele'},
        ),
        migrations.AlterModelOptions(
            name='recipemalt',
            options={'ordering': ['-id'], 'verbose_name': 'Słód', 'verbose_name_plural': 'Słody'},
        ),
        migrations.AlterModelOptions(
            name='recipewater',
            options={'ordering': ['-id'], 'verbose_name': 'Woda', 'verbose_name_plural': 'Woda'},
        ),
        migrations.AlterModelOptions(
            name='recipeyeast',
            options={'ordering': ['-id'], 'verbose_name': 'Drożdże', 'verbose_name_plural': 'Drożdże'},
        ),
        migrations.AlterModelOptions(
            name='style',
            options={'ordering': ['-id'], 'verbose_name': 'Styl Piwa', 'verbose_name_plural': 'Style piwa'},
        ),
        migrations.AlterModelOptions(
            name='water',
            options={'ordering': ['-id'], 'verbose_name': 'Woda', 'verbose_name_plural': 'Wody'},
        ),
        migrations.AlterModelOptions(
            name='yeast',
            options={'ordering': ['-id'], 'verbose_name': 'Drożdże', 'verbose_name_plural': 'Drożdże'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
    ]
