# Generated by Django 3.2.5 on 2021-09-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210915_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipehops',
            name='boiling_time',
            field=models.FloatField(default=1, verbose_name='Czas gotowania'),
            preserve_default=False,
        ),
    ]
