# Generated by Django 3.2.7 on 2021-10-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipehops_boiling_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Zacieranie', 'Zacieranie'), ('Ekstrakty', 'Ekstrakty'), ('Brewkit', 'Brewkit')], max_length=10, null=True, verbose_name='Typ'),
        ),
    ]
