# Generated by Django 3.2.7 on 2021-10-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('m', 'Zacieranie'), ('e', 'Ekstrakty'), ('b', 'Brewkit')], max_length=1, null=True, verbose_name='Typ'),
        ),
    ]
