# Generated by Django 3.2.7 on 2021-10-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='malt',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Czy domyślny?'),
        ),
    ]
