# Generated by Django 3.2.7 on 2021-10-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_malt_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='hops',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Czy domyślny?'),
        ),
        migrations.AddField(
            model_name='yeast',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Czy domyślny?'),
        ),
    ]
