# Generated by Django 3.2.7 on 2021-11-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_rename_mashing_performance_recipe_mashing_efficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='max_carbonation',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='style',
            name='min_carbonation',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
