# Generated by Django 3.2.7 on 2021-11-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20211102_1726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mashing',
        ),
    ]
