# Generated by Django 3.2.7 on 2021-11-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_delete_mashing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='abv',
            new_name='ibu',
        ),
    ]
