# Generated by Django 3.2.7 on 2021-11-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_rename_abv_recipe_ibu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='water',
            name='manufacturer',
        ),
        migrations.DeleteModel(
            name='RecipeWater',
        ),
        migrations.DeleteModel(
            name='Water',
        ),
    ]
