FROM node:14.15-alpine as build

WORKDIR /home/frontend

COPY ./ /home/frontend/

RUN npm install

RUN npm run build --configuration=test

FROM nginx:latest

COPY --from=build /home/frontend/dist/beerappkaFrontend /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'